from __future__ import annotations

ASGI_VERSION = "3.0"
ASGI_SPEC_VERSION = "2.3"
WEBSOCKET_SPEC_VERSION = "2.3"

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8000
DEFAULT_BACKLOG = 2048
DEFAULT_LOG_LEVEL = "info"
DEFAULT_LIFESPAN = "auto"
DEFAULT_ENV_PREFIX = "TIGRCORN"
DEFAULT_WORKERS = 1
DEFAULT_WORKER_CLASS = "local"
DEFAULT_RUNTIME = "auto"
SUPPORTED_RUNTIMES = ("auto", "asyncio", "uvloop")
SUPPORTED_WORKER_CLASS_ALIASES = ("asyncio", "uvloop")
DEFAULT_WORKER_HEALTHCHECK_TIMEOUT = 30.0
DEFAULT_MAX_BODY_SIZE = 16 * 1024 * 1024
DEFAULT_MAX_HEADER_SIZE = 64 * 1024
DEFAULT_HTTP1_MAX_INCOMPLETE_EVENT_SIZE = DEFAULT_MAX_HEADER_SIZE
DEFAULT_HTTP1_BUFFER_SIZE = 64 * 1024
DEFAULT_HTTP2_MAX_CONCURRENT_STREAMS = 128
DEFAULT_HTTP2_MAX_HEADERS_SIZE = DEFAULT_MAX_HEADER_SIZE
DEFAULT_HTTP2_MAX_FRAME_SIZE = 16 * 1024
DEFAULT_HTTP2_INITIAL_CONNECTION_WINDOW_SIZE = 65_535
DEFAULT_HTTP2_INITIAL_STREAM_WINDOW_SIZE = 65_535
DEFAULT_WEBSOCKET_MAX_MESSAGE_SIZE = 16 * 1024 * 1024
DEFAULT_WEBSOCKET_MAX_QUEUE = 32
DEFAULT_MAX_DATAGRAM_SIZE = 1200
DEFAULT_READ_TIMEOUT = 30.0
DEFAULT_WRITE_TIMEOUT = 30.0
DEFAULT_SHUTDOWN_TIMEOUT = 30.0
DEFAULT_KEEPALIVE_TIMEOUT = 5.0
DEFAULT_IDLE_TIMEOUT = 30.0
DEFAULT_SERVER_HEADER = b"tigrcorn"
DEFAULT_QUIC_SECRET = b"tigrcorn-quic-shared-secret"
DEFAULT_PIPE_MODE = "rawframed"
DEFAULT_HTTP_CONTENT_CODINGS = ("gzip", "deflate", "br")
H2_PREFACE = b"PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n"

__all__ = [
    "ASGI_SPEC_VERSION",
    "ASGI_VERSION",
    "DEFAULT_BACKLOG",
    "DEFAULT_ENV_PREFIX",
    "DEFAULT_HOST",
    "DEFAULT_HTTP1_BUFFER_SIZE",
    "DEFAULT_HTTP1_MAX_INCOMPLETE_EVENT_SIZE",
    "DEFAULT_HTTP2_INITIAL_CONNECTION_WINDOW_SIZE",
    "DEFAULT_HTTP2_INITIAL_STREAM_WINDOW_SIZE",
    "DEFAULT_HTTP2_MAX_CONCURRENT_STREAMS",
    "DEFAULT_HTTP2_MAX_FRAME_SIZE",
    "DEFAULT_HTTP2_MAX_HEADERS_SIZE",
    "DEFAULT_HTTP_CONTENT_CODINGS",
    "DEFAULT_IDLE_TIMEOUT",
    "DEFAULT_KEEPALIVE_TIMEOUT",
    "DEFAULT_LIFESPAN",
    "DEFAULT_LOG_LEVEL",
    "DEFAULT_MAX_BODY_SIZE",
    "DEFAULT_MAX_DATAGRAM_SIZE",
    "DEFAULT_MAX_HEADER_SIZE",
    "DEFAULT_PIPE_MODE",
    "DEFAULT_PORT",
    "DEFAULT_QUIC_SECRET",
    "DEFAULT_READ_TIMEOUT",
    "DEFAULT_RUNTIME",
    "DEFAULT_SERVER_HEADER",
    "DEFAULT_SHUTDOWN_TIMEOUT",
    "DEFAULT_WEBSOCKET_MAX_MESSAGE_SIZE",
    "DEFAULT_WEBSOCKET_MAX_QUEUE",
    "DEFAULT_WORKER_CLASS",
    "DEFAULT_WORKER_HEALTHCHECK_TIMEOUT",
    "DEFAULT_WORKERS",
    "DEFAULT_WRITE_TIMEOUT",
    "H2_PREFACE",
    "SUPPORTED_RUNTIMES",
    "SUPPORTED_WORKER_CLASS_ALIASES",
    "WEBSOCKET_SPEC_VERSION",
]
