from __future__ import annotations

FRAME_PADDING = 0x00
FRAME_PING = 0x01
FRAME_ACK = 0x02
FRAME_RESET_STREAM = 0x04
FRAME_STOP_SENDING = 0x05
FRAME_RESET_STREAM_AT = 0x24
FRAME_CRYPTO = 0x06
FRAME_NEW_TOKEN = 0x07
FRAME_STREAM = 0x08
FRAME_MAX_DATA = 0x10
FRAME_MAX_STREAM_DATA = 0x11
FRAME_MAX_STREAMS_BIDI = 0x12
FRAME_MAX_STREAMS_UNI = 0x13
FRAME_DATA_BLOCKED = 0x14
FRAME_STREAM_DATA_BLOCKED = 0x15
FRAME_STREAMS_BLOCKED_BIDI = 0x16
FRAME_STREAMS_BLOCKED_UNI = 0x17
FRAME_NEW_CONNECTION_ID = 0x18
FRAME_RETIRE_CONNECTION_ID = 0x19
FRAME_PATH_CHALLENGE = 0x1A
FRAME_PATH_RESPONSE = 0x1B
FRAME_CONNECTION_CLOSE = 0x1C
FRAME_CONNECTION_CLOSE_APP = 0x1D
FRAME_HANDSHAKE_DONE = 0x1E
FRAME_DATAGRAM = 0x30

_PACKET_SPACE_INITIAL = 'initial'
_PACKET_SPACE_HANDSHAKE = 'handshake'
_PACKET_SPACE_APPLICATION = 'application'
_PACKET_SPACE_ZERO_RTT = '0rtt'
