services:
  tigrcorn-http11-app:
    build:
      context: ../..
      dockerfile: examples/http11_asgi3_demo/Dockerfile
    image: tigrcorn-http11-asgi3-demo:local
    command:
      - tigrcorn
      - examples.http11_asgi3_demo.server:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --protocol
      - http1
      - --http
      - "1.1"
      - --trailer-policy
      - pass
      - --timeout-keep-alive
      - "30"
      - --read-timeout
      - "10"
      - --write-timeout
      - "10"
      - --max-body-size
      - "1048576"
      - --max-header-size
      - "16384"
      - --server-header
      - Tigrcorn-HTTP11-Demo
      - --access-log
    ports:
      - "8011:8000/tcp"

  tigrcorn-http11-uix:
    build:
      context: ../..
      dockerfile: examples/http11_asgi3_demo/Dockerfile.client
    image: tigrcorn-http11-uix-demo:local
    ports:
      - "8012:8080/tcp"
    depends_on:
      - tigrcorn-http11-app
