from __future__ import annotations

ASGI_VERSION = "3.0"
ASGI_SPEC_VERSION = "2.3"
WEBSOCKET_SPEC_VERSION = "2.3"

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8000
DEFAULT_BACKLOG = 2048
DEFAULT_LOG_LEVEL = "info"
DEFAULT_LIFESPAN = "auto"
DEFAULT_MAX_BODY_SIZE = 16 * 1024 * 1024
DEFAULT_MAX_HEADER_SIZE = 64 * 1024
DEFAULT_WEBSOCKET_MAX_MESSAGE_SIZE = 16 * 1024 * 1024
DEFAULT_MAX_DATAGRAM_SIZE = 1200
DEFAULT_READ_TIMEOUT = 30.0
DEFAULT_WRITE_TIMEOUT = 30.0
DEFAULT_SHUTDOWN_TIMEOUT = 30.0
DEFAULT_SERVER_HEADER = b"tigrcorn"
DEFAULT_QUIC_SECRET = b"tigrcorn-quic-shared-secret"
DEFAULT_PIPE_MODE = "rawframed"
H2_PREFACE = b"PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n"
