from __future__ import annotations

from pathlib import Path

STRUCTURED_FIELD_REGISTRY: dict[str, str] = {
    'priority': 'dictionary',
    'signature': 'dictionary',
    'signature-input': 'dictionary',
}

STRUCTURED_FIELD_SAMPLES = [
    {
        'field_name': 'priority',
        'wire_value': 'u=3, i',
        'expected_type': 'dictionary',
    },
    {
        'field_name': 'signature',
        'wire_value': 'sig1=:AQIDBA==:',
        'expected_type': 'dictionary',
    },
    {
        'field_name': 'signature-input',
        'wire_value': 'sig1=("date" "content-digest");created=@1700000000;keyid="test-key"',
        'expected_type': 'dictionary',
    },
]

STALE_STRUCTURED_FIELD_REFERENCE_ALLOWLIST = {
    'docs/conformance/sf9651.json',
    'docs/conformance/sf9651.md',
    'docs/conformance/risk/RISK_REGISTER.json',
    'docs/conformance/risk/RISK_TRACEABILITY.json',
    'docs/notes/feat_matrix.md',
    'docs/notes/feature_reg.md',
    'docs/notes/issue_mat.md',
    'docs/notes/issue_reg.md',
    'docs/notes/risk_reg.md',
    'src/tigrcorn/config/governance_surface.py',
    'tests/test_p8_sf.py',
    'tools/cert/governance_surface.py',
}

RISK_REGISTER = [
    {
        'risk_id': 'R-TRACEABILITY-GOVERNANCE-GAP',
        'title': 'Risk, claim, test, and evidence linkage can drift without machine-readable ownership.',
        'severity': 'high',
        'status': 'mitigated_in_tree',
        'release_gate_blocking': False,
        'owner': 'tigrcorn-maintainers',
        'policy_doc': 'docs/governance/RISK_REGISTER_POLICY.md',
        'feature_refs': ['F-P8-RISK-TRACEABILITY'],
        'claim_refs': ['TC-ROADMAP-P8-RISK-TRACEABILITY', 'TC-GOV-RISK-REGISTER-TRACEABILITY', 'TC-CERT-RELEASE-GATE-GRAPH'],
        'test_refs': ['tests/test_p8_gov.py::test_risk_traceability_graph_is_resolved_and_green'],
        'evidence_refs': ['docs/conformance/risk/RISK_REGISTER.json', 'docs/conformance/risk/RISK_TRACEABILITY.json'],
        'summary': 'Phase 8 closes this by generating risk and traceability graphs and making release gates validate them.',
    },
    {
        'risk_id': 'R-TEST-STYLE-DRIFT',
        'title': 'New forward tests could continue to enter as unittest instead of pytest.',
        'severity': 'medium',
        'status': 'controlled_with_inventory',
        'release_gate_blocking': False,
        'owner': 'tigrcorn-maintainers',
        'policy_doc': 'docs/governance/TEST_STYLE_POLICY.md',
        'feature_refs': ['F-P8-PYTEST-FORWARD'],
        'claim_refs': ['TC-ROADMAP-P8-PYTEST-FORWARD', 'TC-GOV-TEST-STYLE-POLICY'],
        'test_refs': ['tests/test_p8_gov.py::test_legacy_unittest_inventory_is_explicit_and_no_unexpected_files_exist'],
        'evidence_refs': ['LEGACY_UNITTEST_INVENTORY.json', 'docs/governance/TEST_STYLE_POLICY.md'],
        'summary': 'Pytest is the only forward runner in CI, while legacy unittest files are frozen behind an approved inventory.',
    },
    {
        'risk_id': 'R-RFC9651-REFERENCE-DRIFT',
        'title': 'Structured-fields references can drift back to obsolete predecessor wording.',
        'severity': 'high',
        'status': 'mitigated_in_tree',
        'release_gate_blocking': False,
        'owner': 'tigrcorn-maintainers',
        'policy_doc': 'docs/governance/DEFAULT_AUDIT_POLICY.md',
        'feature_refs': ['F-P8-RFC9651-BASELINE'],
        'claim_refs': ['TC-ROADMAP-P8-RFC9651-BASELINE', 'TC-SPEC-STRUCTURED-FIELDS-RFC9651'],
        'test_refs': ['tests/test_p8_sf.py::test_stale_predecessor_references_are_linted_outside_allowlist'],
        'evidence_refs': ['docs/conformance/sf9651.json', 'docs/conformance/sf9651.md'],
        'summary': 'Phase 8 replaces active predecessor-baseline language with RFC 9651 and lints for stale active references.',
    },
    {
        'risk_id': 'R-RELEASE-EVIDENCE-RETENTION',
        'title': 'Interop and performance bundles could drift out of the release gate if they are treated as informal side artifacts.',
        'severity': 'high',
        'status': 'mitigated_in_tree',
        'release_gate_blocking': False,
        'owner': 'tigrcorn-maintainers',
        'policy_doc': 'docs/governance/RISK_REGISTER_POLICY.md',
        'feature_refs': ['F-P8-RELEASE-GATED-EVIDENCE'],
        'claim_refs': ['TC-ROADMAP-P8-RELEASE-GATED-EVIDENCE', 'TC-CERT-INTEROP-RETENTION-BUNDLES', 'TC-CERT-PERFORMANCE-RETENTION-BUNDLES'],
        'test_refs': ['tests/test_p8_gov.py::test_retention_bundles_point_to_existing_release_inputs'],
        'evidence_refs': ['docs/conformance/interop_retention.json', 'docs/conformance/perf_retention.json'],
        'summary': 'The mutable tree now carries explicit retained-bundle manifests that point at canonical release-root evidence and performance inputs.',
    },
]

INTEROP_RETENTION_BUNDLES = [
    {
        'bundle_id': 'independent_release_matrix',
        'path': 'docs/review/conformance/releases/0.3.9/release-0.3.9/tigrcorn-independent-certification-release-matrix',
        'role': 'independent_certification',
    },
    {
        'bundle_id': 'same_stack_replay_matrix',
        'path': 'docs/review/conformance/releases/0.3.9/release-0.3.9/tigrcorn-same-stack-replay-matrix',
        'role': 'same_stack_replay',
    },
    {
        'bundle_id': 'mixed_compatibility_matrix',
        'path': 'docs/review/conformance/releases/0.3.9/release-0.3.9/tigrcorn-mixed-compatibility-release-matrix',
        'role': 'mixed_compatibility',
    },
]

PERFORMANCE_RETENTION_BUNDLES = [
    {
        'bundle_id': 'phase6_current_release',
        'path': 'docs/review/performance/artifacts/phase6_current_release',
        'role': 'current_release_performance_input',
    },
    {
        'bundle_id': 'phase6_reference_baseline',
        'path': 'docs/review/performance/artifacts/phase6_reference_baseline',
        'role': 'baseline_regression_input',
    },
    {
        'bundle_id': 'phase6_matrix',
        'path': 'docs/review/performance/performance_matrix.json',
        'role': 'declared_profile_matrix',
    },
]

APPROVED_LEGACY_UNITTEST_FILES = (
    'tests/test_additional_remaining_work.py',
    'tests/test_app_loader.py',
    'tests/test_certification_policy_alignment.py',
    'tests/test_cli_and_asgi3.py',
    'tests/test_compression_additional.py',
    'tests/test_config_matrix.py',
    'tests/test_conformance_corpus.py',
    'tests/test_connect_rfc9110.py',
    'tests/test_connect_tunnel_h2_h3.py',
    'tests/test_content_coding_policy_local.py',
    'tests/test_default_audits.py',
    'tests/test_dependency_declaration_reconciliation_checkpoint.py',
    'tests/test_documentation_reconciliation.py',
    'tests/test_external_current_release_matrix.py',
    'tests/test_external_independent_peer_release_matrix.py',
    'tests/test_external_interop_runner_matrix.py',
    'tests/test_external_rfc_hardening_candidate_matrix.py',
    'tests/test_flow_scheduler.py',
    'tests/test_hpack_completion_pass.py',
    'tests/test_http_content_coding_rfc9110.py',
    'tests/test_http1_chunked.py',
    'tests/test_http1_hardening_pass.py',
    'tests/test_http1_parser.py',
    'tests/test_http1_rfc9112.py',
    'tests/test_http2_hpack.py',
    'tests/test_http2_rfc9113.py',
    'tests/test_http2_server_push_surface.py',
    'tests/test_http2_state_machine_completion.py',
    'tests/test_http2_websocket_rfc8441.py',
    'tests/test_http3_request_stream_state_machine.py',
    'tests/test_http3_rfc9114.py',
    'tests/test_http3_server.py',
    'tests/test_http3_websocket_rfc9220.py',
    'tests/test_import.py',
    'tests/test_intermediary_proxy_corpus.py',
    'tests/test_lifespan.py',
    'tests/test_observability_workers.py',
    'tests/test_phase1_surface_parity_checkpoint.py',
    'tests/test_phase2_cli_config_surface.py',
    'tests/test_phase2_entity_semantics_checkpoint.py',
    'tests/test_phase2_static_delivery_surface.py',
    'tests/test_phase3_h1_websocket_operator_surface.py',
    'tests/test_phase3_policy_surface.py',
    'tests/test_phase3_strict_rfc_surface.py',
    'tests/test_phase3_transport_core_strictness_checkpoint.py',
    'tests/test_phase4_advanced_protocol_delivery_checkpoint.py',
    'tests/test_phase4_http2_operator_surface.py',
    'tests/test_phase4_operator_surface.py',
    'tests/test_phase4_quic_surface.py',
    'tests/test_phase5_flow_control_bundle.py',
    'tests/test_phase5_intermediary_proxy_corpus.py',
    'tests/test_phase5_origin_contract.py',
    'tests/test_phase5_tls_operator_material_surface.py',
    'tests/test_phase6_observability_surface.py',
    'tests/test_phase6_performance_harness.py',
    'tests/test_phase6_public_lifecycle_and_embedder_contract.py',
    'tests/test_phase7_flag_surface_truth_reconciliation.py',
    'tests/test_phase7_negative_certification.py',
    'tests/test_phase8_promotion_targets.py',
    'tests/test_phase9d1_connect_relay_local_negatives.py',
    'tests/test_phase9f1_tls_cipher_policy_closure.py',
    'tests/test_phase9f2_logging_exporter_closure.py',
    'tests/test_phase9f3_concurrency_keepalive_closure.py',
    'tests/test_phase9g_strict_performance_closure.py',
    'tests/test_phase9h_promotion_evaluator_hardening.py',
    'tests/test_pipe_and_inproc.py',
    'tests/test_prebuffered_reader_and_custom.py',
    'tests/test_profile_resolution.py',
    'tests/test_provisional_all_surfaces_gap_bundle.py',
    'tests/test_provisional_flow_control_gap_bundle.py',
    'tests/test_provisional_http3_gap_bundle.py',
    'tests/test_public_api_cli_mtls_surface.py',
    'tests/test_public_api_tls_cipher_surface.py',
    'tests/test_public_quic_tls_packaging.py',
    'tests/test_qpack_completion.py',
    'tests/test_quic_custom_server.py',
    'tests/test_quic_http3.py',
    'tests/test_quic_http3_additional_rfc.py',
    'tests/test_quic_packets_rfc9000.py',
    'tests/test_quic_primitives.py',
    'tests/test_quic_recovery_live_runtime_integration.py',
    'tests/test_quic_recovery_rfc9002.py',
    'tests/test_quic_rfc_upgrade_paths.py',
    'tests/test_quic_runtime_additions.py',
    'tests/test_quic_stream_flow_state_machine.py',
    'tests/test_quic_tls_external_interop_regressions.py',
    'tests/test_quic_tls_handshake_driver.py',
    'tests/test_quic_tls_rfc9001.py',
    'tests/test_quic_transport_runtime_completion.py',
    'tests/test_rawframed_handler.py',
    'tests/test_registries_models.py',
    'tests/test_release_gates.py',
    'tests/test_response_pipeline_streaming_checkpoint.py',
    'tests/test_response_trailers_rfc9110.py',
    'tests/test_rfc_compliance_hardening.py',
    'tests/test_rfc7838_alt_svc.py',
    'tests/test_rfc8297_early_hints.py',
    'tests/test_scheduler_runtime.py',
    'tests/test_security_compat_utils.py',
    'tests/test_server_http1.py',
    'tests/test_server_http2.py',
    'tests/test_server_unix.py',
    'tests/test_server_websocket.py',
    'tests/test_sessions_streams.py',
    'tests/test_static_delivery_productionization_checkpoint.py',
    'tests/test_tcp_tls_package_owned.py',
    'tests/test_tls13_engine_upgrade.py',
    'tests/test_tls_alpn_rfc7301.py',
    'tests/test_trailer_policy_strict_local.py',
    'tests/test_trailers_rfc9110.py',
    'tests/test_trio_runtime_surface_reconciliation_checkpoint.py',
    'tests/test_websocket_additional_rfc6455.py',
    'tests/test_websocket_frames.py',
    'tests/test_websocket_rfc6455.py',
    'tests/test_websocket_rfc7692.py',
)


def scan_legacy_unittest_files(root: Path) -> list[str]:
    tests_root = root / 'tests'
    detected: list[str] = []
    for path in sorted(tests_root.glob('test_*.py')):
        text = path.read_text(encoding='utf-8')
        if 'import unittest' in text or 'from unittest' in text:
            detected.append(path.as_posix().split(root.as_posix() + '/', 1)[-1])
    return detected


def governance_surface() -> dict[str, object]:
    return {
        'schema_version': 1,
        'structured_fields': {
            'baseline_rfc': 'RFC 9651',
            'obsolete_rfc': 'RFC 8941',
            'registry': STRUCTURED_FIELD_REGISTRY,
            'samples': STRUCTURED_FIELD_SAMPLES,
            'stale_reference_allowlist': sorted(STALE_STRUCTURED_FIELD_REFERENCE_ALLOWLIST),
        },
        'risk_register': list(RISK_REGISTER),
        'interop_retention_bundles': list(INTEROP_RETENTION_BUNDLES),
        'performance_retention_bundles': list(PERFORMANCE_RETENTION_BUNDLES),
        'legacy_unittest_inventory': {
            'forward_runner': 'pytest',
            'approved_legacy_files': list(APPROVED_LEGACY_UNITTEST_FILES),
        },
    }


__all__ = [
    'APPROVED_LEGACY_UNITTEST_FILES',
    'INTEROP_RETENTION_BUNDLES',
    'PERFORMANCE_RETENTION_BUNDLES',
    'RISK_REGISTER',
    'STALE_STRUCTURED_FIELD_REFERENCE_ALLOWLIST',
    'STRUCTURED_FIELD_REGISTRY',
    'STRUCTURED_FIELD_SAMPLES',
    'governance_surface',
    'scan_legacy_unittest_files',
]
