from __future__ import annotations

from pathlib import Path

STRUCTURED_FIELD_REGISTRY: dict[str, str] = {
    'priority': 'dictionary',
    'signature': 'dictionary',
    'signature-input': 'dictionary',
}

STRUCTURED_FIELD_SAMPLES = [
    {
        'field_name': 'priority',
        'wire_value': 'u=3, i',
        'expected_type': 'dictionary',
    },
    {
        'field_name': 'signature',
        'wire_value': 'sig1=:AQIDBA==:',
        'expected_type': 'dictionary',
    },
    {
        'field_name': 'signature-input',
        'wire_value': 'sig1=("date" "content-digest");created=@1700000000;keyid="test-key"',
        'expected_type': 'dictionary',
    },
]

STALE_STRUCTURED_FIELD_REFERENCE_ALLOWLIST = {
    'docs/conformance/sf9651.json',
    'docs/conformance/sf9651.md',
    '.ssot/registry.json',
    'docs/notes/feat_matrix.md',
    'docs/notes/feature_reg.md',
    'docs/notes/issue_mat.md',
    'docs/notes/issue_reg.md',
    'pkgs/tigrcorn-config/src/tigrcorn_config/governance_surface.py',
    'tests/test_p8_sf.py',
    'tools/cert/governance_surface.py',
}

INTEROP_RETENTION_BUNDLES = [
    {
        'bundle_id': 'independent_release_matrix',
        'path': 'docs/review/conformance/releases/0.3.9/release-0.3.9/tigrcorn-independent-certification-release-matrix',
        'role': 'independent_certification',
    },
    {
        'bundle_id': 'same_stack_replay_matrix',
        'path': 'docs/review/conformance/releases/0.3.9/release-0.3.9/tigrcorn-same-stack-replay-matrix',
        'role': 'same_stack_replay',
    },
    {
        'bundle_id': 'mixed_compatibility_matrix',
        'path': 'docs/review/conformance/releases/0.3.9/release-0.3.9/tigrcorn-mixed-compatibility-release-matrix',
        'role': 'mixed_compatibility',
    },
]

PERFORMANCE_RETENTION_BUNDLES = [
    {
        'bundle_id': 'phase6_current_release',
        'path': 'docs/review/performance/artifacts/phase6_current_release',
        'role': 'current_release_performance_input',
    },
    {
        'bundle_id': 'phase6_reference_baseline',
        'path': 'docs/review/performance/artifacts/phase6_reference_baseline',
        'role': 'baseline_regression_input',
    },
    {
        'bundle_id': 'phase6_matrix',
        'path': 'docs/review/performance/performance_matrix.json',
        'role': 'declared_profile_matrix',
    },
]

APPROVED_LEGACY_UNITTEST_FILES = (
    'tests/test_additional_remaining_work.py',
    'tests/test_app_loader.py',
    'tests/test_certification_policy_alignment.py',
    'tests/test_cli_and_asgi3.py',
    'tests/test_compression_additional.py',
    'tests/test_config_matrix.py',
    'tests/test_conformance_corpus.py',
    'tests/test_connect_rfc9110.py',
    'tests/test_connect_tunnel_h2_h3.py',
    'tests/test_content_coding_policy_local.py',
    'tests/test_default_audits.py',
    'tests/test_dependency_declaration_reconciliation_checkpoint.py',
    'tests/test_documentation_reconciliation.py',
    'tests/test_app_interface_cli_flag.py',
    'tests/test_app_interface_config_toml.py',
    'tests/test_app_interface_detection_precedence.py',
    'tests/test_app_interface_env_var.py',
    'tests/test_app_interface_fail_closed_ambiguity.py',
    'tests/test_app_interface_public_api.py',
    'tests/test_asgi3_hot_path_isolation.py',
    'tests/test_compat_dispatch_selection.py',
    'tests/test_compat_http_boundary.py',
    'tests/test_contract_app_dispatch.py',
    'tests/test_contract_core_boundary.py',
    'tests/test_contract_native_public_api.py',
    'tests/test_contract_native_runtime.py',
    'tests/test_external_current_release_matrix.py',
    'tests/test_external_independent_peer_release_matrix.py',
    'tests/test_external_interop_runner_matrix.py',
    'tests/test_external_rfc_hardening_candidate_matrix.py',
    'tests/test_flow_scheduler.py',
    'tests/test_hpack_completion_pass.py',
    'tests/test_http_content_coding_rfc9110.py',
    'tests/test_http1_chunked.py',
    'tests/test_http1_hardening_pass.py',
    'tests/test_http1_parser.py',
    'tests/test_http1_parser_owned_surface.py',
    'tests/test_http1_rfc9112.py',
    'tests/test_http2_hpack.py',
    'tests/test_http2_rfc9113.py',
    'tests/test_http2_rfc9113_server_negatives.py',
    'tests/test_http2_server_push_surface.py',
    'tests/test_http2_state_machine_completion.py',
    'tests/test_http2_websocket_rfc8441.py',
    'tests/test_http3_request_stream_state_machine.py',
    'tests/test_http3_rfc9114.py',
    'tests/test_http3_server.py',
    'tests/test_http3_websocket_rfc9220.py',
    'tests/test_import.py',
    'tests/test_governed_rfc_deep_coverage.py',
    'tests/test_governed_rfc_support_floor.py',
    'tests/test_h11_http1_probe_fixture.py',
    'tests/test_h2_http2_probe_fixture.py',
    'tests/test_h3_asgi3_lab.py',
    'tests/test_h3_http3_probe_fixture.py',
    'tests/test_h3_quic_probe_fixture.py',
    'tests/test_http2_asgi3_demo.py',
    'tests/test_intermediary_proxy_corpus.py',
    'tests/test_lifespan.py',
    'tests/test_lifespan_example.py',
    'tests/test_logging_exporter_closure.py',
    'tests/test_observability_workers.py',
    'tests/test_surface_parity_checkpoint.py',
    'tests/test_cli_config_surface.py',
    'tests/test_entity_semantics_checkpoint.py',
    'tests/test_static_delivery_surface.py',
    'tests/test_h1_websocket_operator_surface.py',
    'tests/test_policy_surface.py',
    'tests/test_strict_rfc_surface.py',
    'tests/test_transport_core_strictness_checkpoint.py',
    'tests/test_advanced_protocol_delivery_checkpoint.py',
    'tests/test_http2_operator_surface.py',
    'tests/test_operator_surface.py',
    'tests/test_quic_surface.py',
    'tests/test_flow_control_bundle.py',
    'tests/test_minimum_certified_intermediary_proxy_corpus.py',
    'tests/test_origin_contract.py',
    'tests/test_tls_operator_material_surface.py',
    'tests/test_observability_surface.py',
    'tests/test_open_loop_benchmark_matrices.py',
    'tests/test_performance_harness.py',
    'tests/test_public_lifecycle_and_embedder_contract.py',
    'tests/test_flag_surface_truth_reconciliation.py',
    'tests/test_negative_certification.py',
    'tests/test_promotion_targets.py',
    'tests/test_connect_relay_local_negatives.py',
    'tests/test_tls_cipher_policy_closure.py',
    'tests/test_concurrency_keepalive_closure.py',
    'tests/test_strict_performance_closure.py',
    'tests/test_promotion_evaluator_hardening.py',
    'tests/test_pipe_and_inproc.py',
    'tests/test_prebuffered_reader_and_custom.py',
    'tests/test_profile_resolution.py',
    'tests/test_provisional_all_surfaces_gap_bundle.py',
    'tests/test_provisional_flow_control_gap_bundle.py',
    'tests/test_provisional_http3_gap_bundle.py',
    'tests/test_public_api_cli_mtls_surface.py',
    'tests/test_public_api_tls_cipher_surface.py',
    'tests/test_public_quic_tls_packaging.py',
    'tests/test_qpack_completion.py',
    'tests/test_quic_custom_server.py',
    'tests/test_quic_http3.py',
    'tests/test_quic_http3_additional_rfc.py',
    'tests/test_quic_packets_rfc9000.py',
    'tests/test_quic_primitives.py',
    'tests/test_quic_recovery_live_runtime_integration.py',
    'tests/test_quic_recovery_rfc9002.py',
    'tests/test_quic_rfc_upgrade_paths.py',
    'tests/test_quic_runtime_additions.py',
    'tests/test_quic_stream_flow_state_machine.py',
    'tests/test_quic_tls_external_interop_regressions.py',
    'tests/test_quic_tls_handshake_driver.py',
    'tests/test_quic_tls_rfc9001.py',
    'tests/test_quic_transport_runtime_completion.py',
    'tests/test_rawframed_handler.py',
    'tests/test_registries_models.py',
    'tests/test_release_gates.py',
    'tests/test_runtime_performance_matrix.py',
    'tests/test_response_pipeline_streaming_checkpoint.py',
    'tests/test_response_trailers_rfc9110.py',
    'tests/test_rfc_compliance_hardening.py',
    'tests/test_rfc7838_alt_svc.py',
    'tests/test_rfc8297_early_hints.py',
    'tests/test_scheduler_runtime.py',
    'tests/test_security_compat_utils.py',
    'tests/test_server_http1.py',
    'tests/test_server_http2.py',
    'tests/test_server_unix.py',
    'tests/test_server_websocket.py',
    'tests/test_sessions_streams.py',
    'tests/test_static_delivery_productionization_checkpoint.py',
    'tests/test_tcp_tls_package_owned.py',
    'tests/test_tls13_engine_upgrade.py',
    'tests/test_tls_alpn_rfc7301.py',
    'tests/test_trailer_policy_strict_local.py',
    'tests/test_trailers_rfc9110.py',
    'tests/test_trio_runtime_surface_reconciliation_checkpoint.py',
    'tests/test_websocket_additional_rfc6455.py',
    'tests/test_websocket_peer_performance_matrix.py',
    'tests/test_websocket_frames.py',
    'tests/test_websocket_rfc6455.py',
    'tests/test_websocket_rfc7692.py',
    'tests/test_websocket_rfc7936.py',
    'tests/test_websocket_rfc8307.py',
    'tests/test_stream_probe_fixtures.py',
    'tests/test_websocket_uix_demo.py',
    'tests/test_webtransport_bidi_stream_context.py',
    'tests/test_webtransport_feature_coverage.py',
    'tests/test_webtransport_mtls_demo.py',
    'tests/test_webtransport_operator_surface.py',
    'tests/test_aioquic_performance_matrix.py',
    'tests/test_ws_wss_probe_fixture.py',
    'tests/test_wss_asgi3_lab.py',
    'tests/test_wt_stream_probe_fixture.py',
)


def scan_legacy_unittest_files(root: Path) -> list[str]:
    tests_root = root / 'tests'
    detected: list[str] = []
    for path in sorted(tests_root.glob('test_*.py')):
        text = path.read_text(encoding='utf-8')
        if 'import unittest' in text or 'from unittest' in text:
            detected.append(path.as_posix().split(root.as_posix() + '/', 1)[-1])
    return detected


def governance_surface() -> dict[str, object]:
    return {
        'schema_version': 1,
        'structured_fields': {
            'baseline_rfc': 'RFC 9651',
            'obsolete_rfc': 'RFC 8941',
            'registry': STRUCTURED_FIELD_REGISTRY,
            'samples': STRUCTURED_FIELD_SAMPLES,
            'stale_reference_allowlist': sorted(STALE_STRUCTURED_FIELD_REFERENCE_ALLOWLIST),
        },
        'interop_retention_bundles': list(INTEROP_RETENTION_BUNDLES),
        'performance_retention_bundles': list(PERFORMANCE_RETENTION_BUNDLES),
        'legacy_unittest_inventory': {
            'forward_runner': 'pytest',
            'approved_legacy_files': list(APPROVED_LEGACY_UNITTEST_FILES),
        },
    }


__all__ = [
    'APPROVED_LEGACY_UNITTEST_FILES',
    'INTEROP_RETENTION_BUNDLES',
    'PERFORMANCE_RETENTION_BUNDLES',
    'STALE_STRUCTURED_FIELD_REFERENCE_ALLOWLIST',
    'STRUCTURED_FIELD_REGISTRY',
    'STRUCTURED_FIELD_SAMPLES',
    'governance_surface',
    'scan_legacy_unittest_files',
]
