from __future__ import annotations

from typing import Any


PROXY_CONTRACT: dict[str, Any] = {
    'trust': {
        'enabled_flag': '--proxy-headers',
        'allowlist_flag': '--forwarded-allow-ips',
        'default_trust_behavior': 'ignore proxy identity headers unless proxy handling is enabled and the immediate peer is trusted',
        'empty_allowlist_behavior': 'when proxy handling is enabled and no allowlist is configured, only loopback peers are trusted',
        'allowlist_tokens': ['*', 'localhost', 'unix', 'single_ip', 'cidr'],
        'untrusted_peer_result': 'preserve socket-derived client/server/scheme and the configured root_path; ignore Forwarded and X-Forwarded-* inputs',
    },
    'precedence': [
        {
            'field': 'client',
            'sources': ['Forwarded.for', 'X-Forwarded-For', 'socket peer'],
            'selection': 'first available source from a trusted immediate peer',
        },
        {
            'field': 'scheme',
            'sources': ['Forwarded.proto', 'X-Forwarded-Proto', 'listener scheme'],
            'selection': 'Forwarded beats X-Forwarded-Proto when both are present',
        },
        {
            'field': 'server',
            'sources': ['Forwarded.host', 'X-Forwarded-Host', 'listener server tuple'],
            'selection': 'Forwarded host beats X-Forwarded-Host when both are present',
        },
        {
            'field': 'root_path',
            'sources': ['configured root_path', 'Forwarded.path', 'X-Forwarded-Prefix', 'X-Script-Name'],
            'selection': 'configured root_path is the base prefix; trusted forwarded prefix data is normalized and appended when distinct',
        },
    ],
    'normalization': [
        'Forwarded processing uses only the first forwarded-element entry.',
        'X-Forwarded-* processing uses only the first CSV token.',
        'Host values normalize bracketed IPv6 host:port forms.',
        'Root paths normalize to leading-slash form and strip trailing slashes except for /.',
        'When both configured root_path and a trusted forwarded prefix are present, Tigrcorn composes them into a single normalized root_path.',
        'Scope path/raw_path stripping occurs only after the effective root_path is finalized.',
    ],
    'runtime_module': 'src/tigrcorn/utils/proxy.py',
}


POLICY_GROUPS: tuple[dict[str, Any], ...] = (
    {
        'claim_id': 'TC-CONTRACT-PROXY-TRUST',
        'surface_id': 'proxy_trust',
        'title': 'Proxy Trust',
        'category': 'Proxy contract',
        'flags': ['--proxy-headers', '--forwarded-allow-ips'],
        'config_paths': ['proxy.proxy_headers', 'proxy.forwarded_allow_ips'],
        'carriers': ['HTTP/1.1', 'HTTP/2', 'HTTP/3', 'WebSocket'],
        'description': 'Trusted proxy admission is explicit and fail-closed.',
        'docs': ['docs/conformance/proxy_contract.md', 'docs/ops/policies.md'],
    },
    {
        'claim_id': 'TC-CONTRACT-PROXY-PRECEDENCE',
        'surface_id': 'proxy_precedence',
        'title': 'Proxy Precedence',
        'category': 'Proxy contract',
        'flags': ['--proxy-headers', '--forwarded-allow-ips', '--root-path'],
        'config_paths': ['proxy.proxy_headers', 'proxy.forwarded_allow_ips', 'proxy.root_path'],
        'carriers': ['HTTP/1.1', 'HTTP/2', 'HTTP/3', 'WebSocket'],
        'description': 'Forwarded and X-Forwarded-* precedence is explicit for client, scheme, host, and root_path.',
        'docs': ['docs/conformance/proxy_contract.md', 'docs/ops/policies.md'],
    },
    {
        'claim_id': 'TC-CONTRACT-PROXY-NORMALIZATION',
        'surface_id': 'proxy_normalization',
        'title': 'Proxy Normalization',
        'category': 'Proxy contract',
        'flags': ['--root-path'],
        'config_paths': ['proxy.root_path'],
        'carriers': ['HTTP/1.1', 'HTTP/2', 'HTTP/3', 'WebSocket'],
        'description': 'Root-path and forwarded-header normalization is frozen and shared across HTTP and WebSocket scope building.',
        'docs': ['docs/conformance/proxy_contract.md', 'docs/ops/policies.md'],
    },
    {
        'claim_id': 'TC-POLICY-CONNECT',
        'surface_id': 'connect',
        'title': 'CONNECT Policy',
        'category': 'RFC policy',
        'flags': ['--connect-policy', '--connect-allow'],
        'config_paths': ['http.connect_policy', 'http.connect_allow'],
        'carriers': ['HTTP/1.1', 'HTTP/2', 'HTTP/3'],
        'description': 'CONNECT relay admission is explicit as deny, relay, or allowlist.',
        'docs': ['docs/ops/policies.md'],
    },
    {
        'claim_id': 'TC-POLICY-TRAILERS',
        'surface_id': 'trailers',
        'title': 'Trailer Policy',
        'category': 'RFC policy',
        'flags': ['--trailer-policy'],
        'config_paths': ['http.trailer_policy'],
        'carriers': ['HTTP/1.1', 'HTTP/2', 'HTTP/3'],
        'description': 'Trailer acceptance and forwarding posture is explicit across supported carriers.',
        'docs': ['docs/ops/policies.md'],
    },
    {
        'claim_id': 'TC-POLICY-CONTENT-CODING',
        'surface_id': 'content_coding',
        'title': 'Content-Coding Policy',
        'category': 'RFC policy',
        'flags': ['--content-coding-policy', '--content-codings'],
        'config_paths': ['http.content_coding_policy', 'http.content_codings'],
        'carriers': ['HTTP/1.1', 'HTTP/2', 'HTTP/3'],
        'description': 'Response content-coding policy and the supported coding allowlist are explicit.',
        'docs': ['docs/ops/policies.md'],
    },
    {
        'claim_id': 'TC-POLICY-H2C',
        'surface_id': 'h2c',
        'title': 'H2C Policy',
        'category': 'Protocol policy',
        'flags': ['--disable-h2c'],
        'config_paths': ['http.enable_h2c'],
        'carriers': ['HTTP/1.1', 'HTTP/2'],
        'description': 'Cleartext HTTP/2 upgrade and preface detection is explicit rather than implicit.',
        'docs': ['docs/ops/policies.md'],
    },
    {
        'claim_id': 'TC-POLICY-ALPN',
        'surface_id': 'alpn',
        'title': 'ALPN Policy',
        'category': 'TLS policy',
        'flags': ['--ssl-alpn'],
        'config_paths': ['tls.alpn_protocols'],
        'carriers': ['TLS over HTTP/1.1', 'TLS over HTTP/2', 'QUIC/HTTP/3'],
        'description': 'ALPN offer ordering and negotiation posture is a stable public control.',
        'docs': ['docs/ops/policies.md'],
    },
    {
        'claim_id': 'TC-POLICY-REVOCATION',
        'surface_id': 'revocation',
        'title': 'OCSP and Revocation Policy',
        'category': 'TLS policy',
        'flags': [
            '--ssl-ocsp-mode',
            '--ssl-ocsp-soft-fail',
            '--ssl-ocsp-cache-size',
            '--ssl-ocsp-max-age',
            '--ssl-crl-mode',
            '--ssl-crl',
            '--ssl-revocation-fetch',
        ],
        'config_paths': [
            'tls.ocsp_mode',
            'tls.ocsp_soft_fail',
            'tls.ocsp_cache_size',
            'tls.ocsp_max_age',
            'tls.crl_mode',
            'tls.crl',
            'tls.revocation_fetch',
        ],
        'carriers': ['TLS over HTTP/1.1', 'TLS over HTTP/2', 'QUIC/HTTP/3'],
        'description': 'OCSP, CRL, and remote revocation-fetch policy is explicit and operator-visible.',
        'docs': ['docs/ops/policies.md'],
    },
    {
        'claim_id': 'TC-POLICY-WEBSOCKET-COMPRESSION',
        'surface_id': 'websocket_compression',
        'title': 'WebSocket Compression Policy',
        'category': 'WebSocket policy',
        'flags': ['--websocket-compression'],
        'config_paths': ['websocket.compression'],
        'carriers': ['WebSocket over HTTP/1.1', 'WebSocket over HTTP/2', 'WebSocket over HTTP/3'],
        'description': 'permessage-deflate policy is explicit across supported WebSocket carriers.',
        'docs': ['docs/ops/policies.md'],
    },
    {
        'claim_id': 'TC-POLICY-LIMITS-TIMEOUTS',
        'surface_id': 'limits_timeouts',
        'title': 'Limits and Timeouts',
        'category': 'Runtime policy',
        'flags': [
            '--timeout-keep-alive',
            '--read-timeout',
            '--write-timeout',
            '--timeout-graceful-shutdown',
            '--max-connections',
            '--max-tasks',
            '--max-streams',
            '--max-body-size',
            '--max-header-size',
            '--http1-max-incomplete-event-size',
            '--http1-buffer-size',
            '--http1-header-read-timeout',
            '--http1-keep-alive',
            '--no-http1-keep-alive',
            '--http2-max-concurrent-streams',
            '--http2-max-headers-size',
            '--http2-max-frame-size',
            '--http2-adaptive-window',
            '--no-http2-adaptive-window',
            '--http2-initial-connection-window-size',
            '--http2-initial-stream-window-size',
            '--http2-keep-alive-interval',
            '--http2-keep-alive-timeout',
            '--websocket-max-message-size',
            '--websocket-max-queue',
            '--idle-timeout',
        ],
        'config_paths': ['http.*', 'websocket.*', 'scheduler.*'],
        'carriers': ['HTTP/1.1', 'HTTP/2', 'HTTP/3', 'WebSocket'],
        'description': 'Resource, buffering, and timeout posture is a reviewed public operator contract.',
        'docs': ['docs/ops/policies.md'],
    },
    {
        'claim_id': 'TC-POLICY-WEBSOCKET-HEARTBEAT',
        'surface_id': 'websocket_heartbeat',
        'title': 'WebSocket Heartbeat',
        'category': 'WebSocket policy',
        'flags': ['--websocket-ping-interval', '--websocket-ping-timeout'],
        'config_paths': ['websocket.ping_interval', 'websocket.ping_timeout'],
        'carriers': ['WebSocket over HTTP/1.1', 'WebSocket over HTTP/2', 'WebSocket over HTTP/3'],
        'description': 'Heartbeat interval and timeout are explicit and carrier-parity tested.',
        'docs': ['docs/ops/policies.md'],
    },
    {
        'claim_id': 'TC-POLICY-DRAIN-ADMISSION',
        'surface_id': 'drain_admission',
        'title': 'Drain and Admission Control',
        'category': 'Runtime policy',
        'flags': ['--limit-concurrency', '--max-connections', '--max-tasks', '--max-streams', '--timeout-graceful-shutdown'],
        'config_paths': [
            'scheduler.limit_concurrency',
            'scheduler.max_connections',
            'scheduler.max_tasks',
            'scheduler.max_streams',
            'http.shutdown_timeout',
        ],
        'carriers': ['HTTP/1.1', 'HTTP/2', 'HTTP/3', 'WebSocket'],
        'description': 'Request, stream, and shutdown admission posture is explicit instead of hidden behind scheduler internals.',
        'docs': ['docs/ops/policies.md'],
    },
)


FLAG_HELP: dict[str, str] = {
    '--proxy-headers': 'Trust Forwarded and X-Forwarded-* identity headers from allowed peers',
    '--forwarded-allow-ips': 'Trusted proxy peers for Forwarded and X-Forwarded-* processing; repeat or use comma-separated values',
    '--root-path': 'Base ASGI root_path applied before trusted proxy prefix normalization',
    '--ssl-alpn': 'ALPN offer list; repeat or use comma-separated values',
    '--ssl-ocsp-mode': 'OCSP revocation mode for peer-certificate validation',
    '--ssl-ocsp-soft-fail': 'Allow OCSP-unavailable validation to continue when strict mode is not required',
    '--ssl-ocsp-cache-size': 'Maximum cached OCSP responses kept in the revocation cache',
    '--ssl-ocsp-max-age': 'Maximum acceptable OCSP response age in seconds',
    '--ssl-crl-mode': 'CRL validation mode for peer-certificate revocation checks',
    '--ssl-crl': 'Local CRL file loaded into the package-owned revocation material set',
    '--ssl-revocation-fetch': 'Enable or disable online revocation fetching for OCSP/CRL validation',
    '--disable-h2c': 'Disable cleartext HTTP/2 upgrade and direct-preface detection on eligible listeners',
    '--websocket-compression': 'WebSocket compression policy across the supported H1, H2, and H3 carriers',
    '--connect-policy': 'CONNECT relay policy: deny, relay, or allowlist',
    '--connect-allow': 'Allowed CONNECT authorities or CIDR targets when CONNECT policy is allowlist',
    '--trailer-policy': 'Trailer handling policy across supported HTTP/1.1, HTTP/2, and HTTP/3 carriers',
    '--content-coding-policy': 'Response content-coding policy: allowlist, identity-only, or strict',
    '--content-codings': 'Supported response codings for allowlist/strict policy; repeat or use comma-separated values',
    '--timeout-keep-alive': 'Idle keep-alive timeout in seconds before an inactive connection is closed',
    '--read-timeout': 'Maximum request read time in seconds for package-owned transports',
    '--write-timeout': 'Maximum response write time in seconds for package-owned transports',
    '--timeout-graceful-shutdown': 'Graceful-drain timeout in seconds before shutdown stops waiting on active work',
    '--limit-concurrency': 'Maximum concurrently admitted request/stream work across the production scheduler',
    '--max-connections': 'Maximum simultaneously open client connections',
    '--max-tasks': 'Maximum concurrently scheduled background work tasks',
    '--max-streams': 'Maximum concurrently admitted logical streams or units of work per session policy',
    '--max-body-size': 'Maximum accepted request body size in bytes',
    '--max-header-size': 'Maximum accepted request-header bytes before rejection',
    '--http1-max-incomplete-event-size': 'Maximum buffered incomplete HTTP/1.1 request-head bytes before rejection',
    '--http1-buffer-size': 'HTTP/1.1 incremental read buffer size in bytes',
    '--http1-header-read-timeout': 'HTTP/1.1 request-head read timeout in seconds',
    '--http1-keep-alive': 'Enable HTTP/1.1 connection persistence',
    '--http2-max-concurrent-streams': 'Advertised HTTP/2 MAX_CONCURRENT_STREAMS value for peer-created streams',
    '--http2-max-headers-size': 'HTTP/2-specific decoded header-list size cap',
    '--http2-max-frame-size': 'Advertised HTTP/2 MAX_FRAME_SIZE for inbound peer frames',
    '--http2-adaptive-window': 'Enable adaptive HTTP/2 receive-window growth',
    '--http2-initial-connection-window-size': 'HTTP/2 connection-level receive window target',
    '--http2-initial-stream-window-size': 'Advertised HTTP/2 INITIAL_WINDOW_SIZE for peer-created streams',
    '--http2-keep-alive-interval': 'Idle interval before sending an HTTP/2 connection-level PING',
    '--http2-keep-alive-timeout': 'Timeout in seconds for an HTTP/2 keep-alive PING acknowledgement',
    '--websocket-max-message-size': 'Maximum accepted WebSocket message size in bytes',
    '--websocket-max-queue': 'Maximum queued inbound WebSocket messages before transport backpressure applies',
    '--websocket-ping-interval': 'Outbound WebSocket heartbeat interval in seconds',
    '--websocket-ping-timeout': 'WebSocket heartbeat acknowledgement timeout in seconds',
    '--idle-timeout': 'Idle application/session timeout in seconds',
}


def flag_help(flag: str, fallback: str | None = None) -> str | None:
    return FLAG_HELP.get(flag, fallback)


def policy_groups() -> tuple[dict[str, Any], ...]:
    return POLICY_GROUPS


def policy_group_by_claim_id(claim_id: str) -> dict[str, Any]:
    for group in POLICY_GROUPS:
        if group['claim_id'] == claim_id:
            return group
    raise KeyError(claim_id)
