name: publish-npm

on:
  push:
    tags:
      - "v*"
  release:
    types: [prereleased, published]
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: "22"
          registry-url: https://registry.npmjs.org
      - name: Install npm workspace
        run: npm install
      - name: Typecheck npm packages
        run: npm run typecheck
      - name: Build npm packages
        run: npm run build
      - name: Test npm packages
        run: npm test
      - name: Publish npm packages
        run: npm publish --workspace packages/wt-peer-probes --access public --provenance
